import random
import numpy as np
import time
import sys
import os

# Add parent directory to path to import src
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.compressor import NoisePacker
from src.config import *
from src.prngs import PRNG_REGISTRY

def main():
    print(f"--- NOISEPACKER MULTI-ALGO DEMO ---")
    print(f"Scenario: Data is generated by Mixed PRNGs (MT, LCG, Xorshift).")
    print(f"Goal: Can we identify which PRNG was used and find the seed?")
    print(f"Note: Using Staggered Search (MT=Base, LCG=Base+2R, XOR=Base+4R).")
    print("-" * 60)

    n_chunks = 6
    chunk_len_bytes = (BLOCKS_PER_CHUNK * BLOCK_SIZE) // 8
    chunk_len_bits = BLOCKS_PER_CHUNK * BLOCK_SIZE

    data_chunks = []
    hidden_info = []

    # Create data with different PRNGs
    rng_maker = random.Random(42)

    for i in range(n_chunks):
        algo_id = i % 3
        prng_class = PRNG_REGISTRY[algo_id]
        prng = prng_class()

        # Pick a seed
        base_seed = 500 # The "Base" seed the packer is near

        # Apply the Staggered Shift to generate the hidden data
        # This simulates that the data comes from the "territory" assigned to that PRNG
        shift = algo_id * (SEARCH_RADIUS * 2)

        # Add a small random offset within radius
        offset = rng_maker.randint(-100, 100)
        secret_seed = base_seed + shift + offset

        prng.seed(secret_seed)

        hidden_info.append((algo_id, secret_seed))

        chunk_bytes = prng.randbytes(chunk_len_bytes)

        # Convert to numpy
        chunk_int = int.from_bytes(chunk_bytes, 'big')
        bits_str = format(chunk_int, f'0{chunk_len_bits}b')[-chunk_len_bits:]
        flat_bits = np.array([int(b) for b in bits_str], dtype=np.uint8)
        chunk_numpy = flat_bits.reshape((BLOCKS_PER_CHUNK, BLOCK_SIZE))

        data_chunks.append(chunk_numpy)

    # Run Compressor
    packer = NoisePacker()

    print(f"{'#ID':<5} | {'ALGO':<5} | {'SEED':<8} | {'FOUND':<8} | {'STATUS'}")
    print("-" * 60)

    for i in range(n_chunks):
        # Set packer current seed to the Base
        packer.current_seed = 500

        is_compressed, cost, delta = packer.process_chunk(data_chunks[i])

        status = "✅ MATCH" if is_compressed else "❌ FAIL"

        h_algo, h_seed = hidden_info[i]
        algo_name = ["MT", "LCG", "XOR"][h_algo]

        found_seed = packer.current_seed

        if is_compressed:
             if found_seed == h_seed:
                 status += " (Exact)"
             else:
                 status += " (Collision)"

        print(f"#{i:<5} | {algo_name:<5} | {h_seed:<8} | {found_seed:<8} | {status}")

if __name__ == "__main__":
    main()